/*
Programme written by :-
Rishabh Mehta
XII-D		2003-04

Ticket booth :-
This programme takes in account of number of
entry and money paid by them.
*/

#include<iostream.h>
#include<conio.h>

class ticket
{
 int ppl;
 float amt;

 public:
 ticket()
 {
  ppl=0;
  amt=0;
 }
 void ptotal();
 void patotal();
 void display();
};

void ticket::ptotal()
{
 ppl+=1;
}

void ticket::patotal()
{
 ppl+=1;
 amt+=2.50;
}

void ticket::display()
{
 clrscr();
 cout<<"Total Visitor                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ticket ???	: y

Any More people waiting : y
Want to buy ticket ???	: y

Any More people waiting : y
Want to buy ticket ???	: y

Any More people waiting : y
Want to buy ticket ???	: n

Any More people waiting : y
Want to buy ticket ???	: n

Any More people waiting : n

Total Visitors = 4
Total Collections = Rs 5
Total Tickets Sold = 2
*/




                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                





                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
