#include<iostream.h>
#include<conio.h>
void main()
{
clrscr();
int n;
cout<<"Enter the value of n: ";
cin>>n;
for(int i=1; i<=n; i++)
{
for(int j=n-1; j>=i; j--)
cout<<" "; int k=1;
for(j=1; j <=i;j++)
{cout<<"*";  for(int p = 1 ; p <k ; p++)
			cout<<" ";
			k+=2;
			cout<<"*"
cout<<endl;
}
/*for(int m=0; m<=i+2; m++)
cout<<" ";
cout<<"*";
cout<<endl;
} */
getch();
}



                                                                                
                                                                                
                                                                                
                                                                                

                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
