#include<iostream.h>
#include<conio.h>
#include<math.h>
void main()
{
clrscr();
int a,b;
cout<<"Enter the first value"<<"\n";
cin>>a;
cout<<"Enter the second value"<<"\n";
cin>>b;
cout<<"Sum of "<<a<<"+"<<b<<"="<<a+b<<"\n";
cout<<"Difference of "<<a<<"-"<<b<<"="<<a-b<<"\n";
cout<<"Product of "<<a<<"*"<<b<<"="<<a*b<<"\n";
cout<<"Remainder is "<<a%b<<"\n";
cout<<"Division "<<a<<" / "<<b<<"= "<<a/b;
getch();
}

