//This program prints out the shape of 'Z'.
//Program created by Rahul Jain.

#include<iostream.h>
#include<conio.h>
void main()
{
 clrscr();
 int n;
 cout<<"Enter the value of n: ";
 cin>>n;
 cout<<endl;

	for(int i=1; i<=n; i++)
	cout<<"*";
	cout<<endl;

	for(int j=2; j<=n-1; j++)
	 {
	  for(int k=n-1; k>=j; k--)
	  cout<<" ";
	  cout<<"*";
	  cout<<endl;
	 }

	for(int m=1; m<=n;m++)
	cout<<"*";

 getch();
}



/*




OUTPUT:


Enter the value of n: 7

*******
     *
    *
   *
  *
 *
*******



*/



                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                

                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                






