#include<iostream.h>
#include<conio.h>
#include<stdio.h>
#include<process.h>

void read(int a[], int n)
{
cout<<"No. of records? ";
cin>>n;
for(int i=0; i<n; i++)
cin>>a[i];
}

void display(int a[], int n)
{
cout<<"\nThe elements of the array are: "<<endl;
for(int i=0; i<n; i++)
cout<<a[i]<<endl;
}

void merge(int a[], int b[], int c[], int m, int n)
{

}


cout

void main()
{
clrscr();

getch();
}